import { useState, useEffect, useCallback, useRef } from 'react';
import {
  Zap,
  Copy,
  Download,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Loader2,
  Plus,
  Trash2,
  Eye,
  EyeOff,
  RefreshCw,
  Shield,
  Package,
  Terminal,
  ArrowRight,
  Sparkles,
} from 'lucide-react';
import { cn } from '../utils/cn';
import { useAppStore } from '../store/appStore';
import { PROMPT_TEMPLATES, EXAMPLE_PROMPTS } from '../utils/constants';
import { formatDuration } from '../utils/formatters';
import type {
  GenerationResult,
  ValidationReport,
  EnvironmentVariable,
  TransportType,
} from '../types/mcp.types';
import { nanoid } from '../utils/nanoid';

// --- Simulated MCP code generation ---

function generateMockCode(prompt: string, envVars: EnvironmentVariable[]): string {
  const serverName = prompt.split(' ').slice(0, 3).map(w => w.toLowerCase().replace(/[^a-z]/g, '')).filter(Boolean).join('-') || 'mcp-server';
  const tools = detectTools(prompt);
  
  const envBlock = envVars.length
    ? `\n// Environment variable validation\nconst requiredEnvVars = [${envVars.map(e => `'${e.name}'`).join(', ')}] as const;\nfor (const envVar of requiredEnvVars) {\n  if (!process.env[envVar]) throw new Error(\`\${envVar} environment variable is required\`);\n}\n\n${envVars.map(e => `const ${e.name} = process.env.${e.name}!;`).join('\n')}`
    : '';

  return `#!/usr/bin/env node
/**
 * ${serverName.toUpperCase().replace(/-/g, ' ')} MCP Server
 * Generated by MCPForge — https://mcpforge.dev
 * 
 * This server provides tools for ${prompt.slice(0, 80)}...
 */
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  type Tool,
} from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
${envBlock ? envBlock + '\n' : ''}
// ============================================================
// Tool Definitions
// ============================================================

${tools.map(tool => `/** ${tool.description} */
const ${tool.name.toUpperCase()}_SCHEMA = z.object({
  ${tool.inputs.map(inp => `${inp.name}: z.${inp.type}().describe("${inp.desc}")`).join(',\n  ')}
});`).join('\n\n')}

// ============================================================
// Server Instance
// ============================================================

const server = new Server(
  {
    name: "${serverName}",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// ============================================================
// Tool Registry
// ============================================================

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
${tools.map(tool => `    {
      name: "${tool.name}",
      description: "${tool.description}",
      inputSchema: {
        type: "object",
        properties: {
          ${tool.inputs.map(inp => `${inp.name}: { type: "${inp.jsType}", description: "${inp.desc}" }`).join(',\n          ')}
        },
        required: [${tool.inputs.filter(i => i.required).map(i => `"${i.name}"`).join(', ')}],
      },
    }`).join(',\n')}
  ] satisfies Tool[],
}));

// ============================================================
// Tool Handlers
// ============================================================

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
${tools.map(tool => `      case "${tool.name}": {
        const parsed = ${tool.name.toUpperCase()}_SCHEMA.safeParse(args);
        if (!parsed.success) {
          return {
            content: [{ type: "text", text: \`Validation error: \${parsed.error.message}\` }],
            isError: true,
          };
        }
        
        // TODO: Implement ${tool.name} logic
        const response = await fetch(\`${tool.apiEndpoint}\`, {
          method: "${tool.method}",
          headers: {
            "Content-Type": "application/json",
            ${envVars.length ? `"Authorization": \`Bearer \${${envVars[0]?.name || 'API_KEY'}}\`` : '"Authorization": "Bearer YOUR_TOKEN"'},
          },
          signal: AbortSignal.timeout(30000),
        });

        if (!response.ok) {
          throw new Error(\`API request failed: \${response.status} \${response.statusText}\`);
        }

        const data = await response.json();
        return {
          content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        };
      }`).join('\n\n')}

      default:
        return {
          content: [{ type: "text", text: \`Unknown tool: \${name}\` }],
          isError: true,
        };
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      content: [{ type: "text", text: \`Error executing \${name}: \${message}\` }],
      isError: true,
    };
  }
});

// ============================================================
// Server Startup
// ============================================================

/**
 * Initialize and start the MCP server using stdio transport.
 * This allows the server to communicate with MCP clients via stdin/stdout.
 */
async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("${serverName} MCP server running on stdio");
}

main().catch((error) => {
  console.error("Fatal error starting server:", error);
  process.exit(1);
});`;
}

interface ToolDef {
  name: string;
  description: string;
  method: string;
  apiEndpoint: string;
  inputs: { name: string; type: string; jsType: string; desc: string; required: boolean }[];
}

function detectTools(prompt: string): ToolDef[] {
  const p = prompt.toLowerCase();
  const tools: ToolDef[] = [];

  if (p.includes('github') || p.includes('repo') || p.includes('pr')) {
    tools.push({
      name: 'list_repositories',
      description: 'List GitHub repositories for an owner',
      method: 'GET',
      apiEndpoint: 'https://api.github.com/users/${parsed.data.owner}/repos',
      inputs: [
        { name: 'owner', type: 'string', jsType: 'string', desc: 'GitHub username or org name', required: true },
        { name: 'per_page', type: 'number', jsType: 'number', desc: 'Results per page (max 100)', required: false },
      ],
    });
    tools.push({
      name: 'create_issue',
      description: 'Create a new GitHub issue in a repository',
      method: 'POST',
      apiEndpoint: 'https://api.github.com/repos/${parsed.data.owner}/${parsed.data.repo}/issues',
      inputs: [
        { name: 'owner', type: 'string', jsType: 'string', desc: 'Repository owner', required: true },
        { name: 'repo', type: 'string', jsType: 'string', desc: 'Repository name', required: true },
        { name: 'title', type: 'string', jsType: 'string', desc: 'Issue title', required: true },
        { name: 'body', type: 'string', jsType: 'string', desc: 'Issue body in markdown', required: false },
      ],
    });
  }

  if (p.includes('slack') || p.includes('message') || p.includes('channel')) {
    tools.push({
      name: 'send_message',
      description: 'Send a message to a Slack channel',
      method: 'POST',
      apiEndpoint: 'https://slack.com/api/chat.postMessage',
      inputs: [
        { name: 'channel', type: 'string', jsType: 'string', desc: 'Channel ID or name', required: true },
        { name: 'text', type: 'string', jsType: 'string', desc: 'Message text', required: true },
      ],
    });
    tools.push({
      name: 'list_channels',
      description: 'List all channels in the Slack workspace',
      method: 'GET',
      apiEndpoint: 'https://slack.com/api/conversations.list',
      inputs: [
        { name: 'limit', type: 'number', jsType: 'number', desc: 'Maximum channels to return', required: false },
      ],
    });
  }

  if (p.includes('jira') || p.includes('issue') || p.includes('sprint')) {
    tools.push({
      name: 'search_issues',
      description: 'Search Jira issues using JQL',
      method: 'GET',
      apiEndpoint: 'https://${JIRA_BASE_URL}/rest/api/3/search?jql=${parsed.data.jql}',
      inputs: [
        { name: 'jql', type: 'string', jsType: 'string', desc: 'JQL query string', required: true },
        { name: 'max_results', type: 'number', jsType: 'number', desc: 'Maximum results', required: false },
      ],
    });
  }

  if (p.includes('notion') || p.includes('page') || p.includes('database')) {
    tools.push({
      name: 'search_pages',
      description: 'Search Notion pages and databases',
      method: 'POST',
      apiEndpoint: 'https://api.notion.com/v1/search',
      inputs: [
        { name: 'query', type: 'string', jsType: 'string', desc: 'Search query', required: true },
        { name: 'filter_type', type: 'string', jsType: 'string', desc: 'page or database', required: false },
      ],
    });
  }

  if (p.includes('linear') || p.includes('project') || p.includes('cycle')) {
    tools.push({
      name: 'list_issues',
      description: 'List Linear issues with filters',
      method: 'POST',
      apiEndpoint: 'https://api.linear.app/graphql',
      inputs: [
        { name: 'team_id', type: 'string', jsType: 'string', desc: 'Team identifier', required: true },
        { name: 'state', type: 'string', jsType: 'string', desc: 'Issue state filter', required: false },
      ],
    });
  }

  // Generic fallback
  if (tools.length === 0) {
    const words = prompt.split(' ').filter(w => w.length > 4);
    const action = words[0]?.toLowerCase() || 'search';
    const target = words[1]?.toLowerCase() || 'items';
    tools.push({
      name: `${action}_${target}`.replace(/[^a-z_]/g, '').slice(0, 30),
      description: `${action.charAt(0).toUpperCase() + action.slice(1)} ${target} from the service`,
      method: 'GET',
      apiEndpoint: 'https://api.example.com/v1/items',
      inputs: [
        { name: 'query', type: 'string', jsType: 'string', desc: 'Search query or identifier', required: true },
        { name: 'limit', type: 'number', jsType: 'number', desc: 'Maximum results to return', required: false },
      ],
    });
    tools.push({
      name: `create_${target}`.replace(/[^a-z_]/g, '').slice(0, 30),
      description: `Create a new ${target} in the service`,
      method: 'POST',
      apiEndpoint: 'https://api.example.com/v1/items',
      inputs: [
        { name: 'name', type: 'string', jsType: 'string', desc: 'Name of the item to create', required: true },
        { name: 'data', type: 'string', jsType: 'string', desc: 'JSON data for the item', required: false },
      ],
    });
  }

  return tools.slice(0, 5);
}

function buildValidationReport(_code: string): ValidationReport {
  const score = Math.floor(Math.random() * 20) + 78; // 78-98
  return {
    passed: score >= 70,
    syntaxErrors: [],
    structuralWarnings:
      score < 85
        ? [{ type: 'missing_error_handling', message: 'Some handlers lack comprehensive error wrapping', suggestion: 'Wrap all async handlers in try/catch blocks' }]
        : [],
    missingExports: [],
    detectedDependencies: ['@modelcontextprotocol/sdk', 'zod'],
    securityFlags: [],
    envVarReport: { used: [], undeclared: [], unused: [] },
    score,
    readinessLevel: score >= 90 ? 'excellent' : score >= 70 ? 'ready' : 'needs-work',
    suggestions: score < 90 ? ['Add JSDoc comments to tool handlers', 'Consider adding input length validation'] : [],
    canDeploy: score >= 70,
  };
}

// --- Sub-components ---

function EnvVarRow({
  envVar,
  index,
  onChange,
  onRemove,
}: {
  envVar: EnvironmentVariable;
  index: number;
  onChange: (index: number, field: keyof EnvironmentVariable, value: string | boolean) => void;
  onRemove: (index: number) => void;
}) {
  const [showValue, setShowValue] = useState(false);

  const isSecretName =
    /(_SECRET|_KEY|_TOKEN|_PASSWORD|_PRIVATE)/i.test(envVar.name);

  return (
    <div className="flex items-center gap-2">
      <input
        type="text"
        value={envVar.name}
        onChange={(e) => onChange(index, 'name', e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g, ''))}
        placeholder="VAR_NAME"
        className={cn(
          'flex-1 rounded-lg border px-3 py-2 font-mono text-xs uppercase',
          'bg-white text-slate-900 placeholder:text-slate-300',
          'border-slate-200 focus:border-violet-400 focus:outline-none focus:ring-2 focus:ring-violet-100',
        )}
      />
      <div className="relative flex-1">
        <input
          type={showValue ? 'text' : 'password'}
          value={envVar.value}
          onChange={(e) => onChange(index, 'value', e.target.value)}
          placeholder="value"
          className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 pr-8 text-xs text-slate-900 placeholder:text-slate-300 focus:border-violet-400 focus:outline-none focus:ring-2 focus:ring-violet-100"
        />
        <button
          type="button"
          onClick={() => setShowValue(!showValue)}
          className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
        >
          {showValue ? <EyeOff className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}
        </button>
      </div>
      {isSecretName && (
        <span title="This will be encrypted" className="text-amber-500">
          <Shield className="h-3.5 w-3.5" />
        </span>
      )}
      <button
        onClick={() => onRemove(index)}
        className="rounded-lg p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-500"
      >
        <Trash2 className="h-3.5 w-3.5" />
      </button>
    </div>
  );
}

function ValidationBadge({ score }: { score: number }) {
  const color =
    score >= 90 ? 'emerald' : score >= 70 ? 'blue' : score >= 50 ? 'amber' : 'red';
  const label =
    score >= 90 ? 'Excellent' : score >= 70 ? 'Good' : score >= 50 ? 'Needs Work' : 'Critical';

  return (
    <span
      className={cn(
        'inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold',
        color === 'emerald' && 'bg-emerald-100 text-emerald-700',
        color === 'blue' && 'bg-blue-100 text-blue-700',
        color === 'amber' && 'bg-amber-100 text-amber-700',
        color === 'red' && 'bg-red-100 text-red-700',
      )}
    >
      {score}/100 · {label}
    </span>
  );
}

// --- Main Forge Page ---

type GenerationState = 'idle' | 'generating' | 'validating' | 'complete' | 'error';

const GENERATION_STEPS = [
  { label: 'Analyzing prompt', pct: 15 },
  { label: 'Generating TypeScript', pct: 60 },
  { label: 'Running validation', pct: 85 },
  { label: 'Finalizing', pct: 100 },
];

interface ForgePageProps {
  onNavigate: (view: string) => void;
}

export default function ForgePage({ onNavigate }: ForgePageProps) {
  const { state, dispatch } = useAppStore();
  const { user } = state;
  const plan = user?.billing_plan ?? 'free';

  const [prompt, setPrompt] = useState('');
  const [envVars, setEnvVars] = useState<EnvironmentVariable[]>([]);
  const [transport, setTransport] = useState<TransportType>('stdio');
  const [genState, setGenState] = useState<GenerationState>('idle');
  const [progress, setProgress] = useState(0);
  const [progressLabel, setProgressLabel] = useState('');
  const [result, setResult] = useState<GenerationResult | null>(null);
  const [copied, setCopied] = useState(false);

  const [placeholderIdx, setPlaceholderIdx] = useState(0);
  const [activeTab, setActiveTab] = useState<'code' | 'validation' | 'readme'>('code');
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const abortRef = useRef<AbortController | null>(null);

  // Rotate placeholder text
  useEffect(() => {
    const interval = setInterval(() => {
      setPlaceholderIdx((i) => (i + 1) % EXAMPLE_PROMPTS.length);
    }, 4000);
    return () => clearInterval(interval);
  }, []);

  // Auto-resize textarea
  useEffect(() => {
    const ta = textareaRef.current;
    if (!ta) return;
    ta.style.height = 'auto';
    ta.style.height = `${Math.min(Math.max(ta.scrollHeight, 96), 400)}px`;
  }, [prompt]);

  // Keyboard shortcuts
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
        e.preventDefault();
        if (genState === 'idle' && prompt.length >= 10) handleGenerate();
      }
      if (e.key === 'Escape' && genState === 'generating') {
        abortRef.current?.abort();
        setGenState('idle');
        setProgress(0);
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [genState, prompt]);

  const handleGenerate = useCallback(async () => {
    // Quota check
    if (plan === 'free' && (user?.mcp_server_count ?? 0) >= 2) {
      dispatch({ type: 'OPEN_UPGRADE_MODAL', payload: 'quota_exceeded' });
      return;
    }

    if (prompt.trim().length < 10) return;

    setGenState('generating');
    setProgress(0);
    setResult(null);
    abortRef.current = new AbortController();

    const startTime = Date.now();

    try {
      // Simulate generation pipeline with realistic timing
      for (let i = 0; i < GENERATION_STEPS.length; i++) {
        const step = GENERATION_STEPS[i];
        setProgressLabel(step.label);

        // Animate progress to step target
        const stepDuration = [800, 3500, 1200, 600][i];
        const startPct = i === 0 ? 0 : GENERATION_STEPS[i - 1].pct;
        const endPct = step.pct;
        const frames = 30;
        for (let f = 0; f <= frames; f++) {
          if (abortRef.current.signal.aborted) throw new Error('Aborted');
          await new Promise((r) => setTimeout(r, stepDuration / frames));
          setProgress(startPct + ((endPct - startPct) * f) / frames);
        }
      }

      // Generate code
      const generatedCode = generateMockCode(prompt, envVars);
      const validationReport = buildValidationReport(generatedCode);

      setGenState('validating');

      const newServer = {
        id: `srv_${nanoid(8)}`,
        user_id: user?.id ?? 'demo',
        name: prompt.split(' ').filter(w => w.length > 3).slice(0, 2).map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join('') + 'MCP',
        description: prompt.slice(0, 120),
        generated_code: generatedCode,
        status: 'deployed' as const,
        environment_variables: envVars.map(e => ({ ...e, value: e.isSecret ? '***' : e.value })),
        tool_count: (generatedCode.match(/name: "/g) || []).length,
        resource_count: 0,
        last_invoked_at: null,
        deployment_region: 'us-east-1',
        is_public: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        invocation_count: 0,
        validation_score: validationReport.score,
        readme_content: null,
      };

      const generationResult: GenerationResult = {
        success: true,
        generatedCode,
        config: {
          serverId: newServer.id,
          serverName: newServer.name,
          version: '1.0.0',
          transport: 'StdioServerTransport',
          tools: [],
          resources: [],
          prompts: [],
          environmentVariables: envVars,
          capabilities: { tools: true, resources: false, prompts: false, streaming: false },
        },
        validationReport,
        tokenUsage: {
          promptTokens: Math.floor(prompt.length * 1.3),
          completionTokens: Math.floor(generatedCode.length * 0.25),
          totalTokens: Math.floor(prompt.length * 1.3 + generatedCode.length * 0.25),
          estimatedCostUSD: 0,
          modelUsed: 'llama-3.1-70b-versatile',
        },
        generationTimeMs: Date.now() - startTime,
        cacheHit: false,
        serverId: newServer.id,
      };

      setResult(generationResult);
      setGenState('complete');
      dispatch({ type: 'ADD_SERVER', payload: newServer });
      dispatch({
        type: 'ADD_NOTIFICATION',
        payload: {
          id: Date.now().toString(),
          type: 'success',
          title: '🚀 MCP Server Generated!',
          message: `${newServer.name} deployed with score ${validationReport.score}/100`,
          timestamp: new Date().toISOString(),
        },
      });
    } catch (err) {
      if ((err as Error).message === 'Aborted') {
        setGenState('idle');
      } else {
        setGenState('error');
        dispatch({
          type: 'ADD_NOTIFICATION',
          payload: {
            id: Date.now().toString(),
            type: 'error',
            title: 'Generation failed',
            message: 'An error occurred during code generation. Please try again.',
            timestamp: new Date().toISOString(),
          },
        });
      }
    }
  }, [prompt, envVars, user, plan, dispatch]);

  const handleCopy = () => {
    if (result?.generatedCode) {
      navigator.clipboard.writeText(result.generatedCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    if (!result?.generatedCode) return;
    const blob = new Blob([result.generatedCode], { type: 'text/typescript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${result.config.serverName.toLowerCase()}.ts`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const addEnvVar = () => {
    setEnvVars([...envVars, { name: '', value: '', isSecret: false }]);
  };

  const updateEnvVar = (index: number, field: keyof EnvironmentVariable, value: string | boolean) => {
    const updated = [...envVars];
    (updated[index] as any)[field] = value;
    if (field === 'name' && /(_SECRET|_KEY|_TOKEN|_PASSWORD)/i.test(value as string)) {
      updated[index].isSecret = true;
    }
    setEnvVars(updated);
  };

  const removeEnvVar = (index: number) => {
    setEnvVars(envVars.filter((_, i) => i !== index));
  };

  const charCount = prompt.length;
  const charColor = charCount > 1800 ? 'text-red-500' : charCount > 1500 ? 'text-amber-500' : 'text-slate-400';

  return (
    <div className="mx-auto max-w-7xl p-4 sm:p-6">
      {/* Page header */}
      <div className="mb-6">
        <h1 className="text-2xl font-black text-slate-900">
          <span className="bg-gradient-to-r from-violet-600 to-indigo-600 bg-clip-text text-transparent">Forge</span> a New MCP Server
        </h1>
        <p className="mt-0.5 text-sm text-slate-500">
          Describe what you want your MCP server to do — AI handles the rest. ⌘+Enter to generate.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 xl:grid-cols-5">
        {/* Left panel — Input */}
        <div className="space-y-4 xl:col-span-2">
          {/* Prompt input */}
          <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div className="border-b border-slate-100 px-4 py-3">
              <h2 className="text-sm font-bold text-slate-900">Describe Your MCP Server</h2>
              <p className="text-xs text-slate-400">Be specific about the APIs, tools, and authentication method</p>
            </div>
            <div className="p-4">
              <div className="relative">
                <textarea
                  ref={textareaRef}
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder={EXAMPLE_PROMPTS[placeholderIdx]}
                  maxLength={2000}
                  className={cn(
                    'w-full resize-none rounded-xl border bg-slate-50 p-4 text-sm text-slate-900',
                    'placeholder:text-slate-300 focus:bg-white focus:outline-none focus:ring-2 focus:ring-violet-300',
                    'border-slate-200 transition-all min-h-[96px]',
                  )}
                />
                <div className={cn('absolute bottom-3 right-3 text-xs', charColor)}>
                  {charCount}/2000
                </div>
              </div>

              {/* Quick enhancement chips */}
              {prompt.length > 5 && prompt.length < 100 && (
                <div className="mt-2 flex flex-wrap gap-1.5">
                  {['+ Auth', '+ Pagination', '+ Webhooks', '+ Rate Limiting', '+ Retry Logic'].map((chip) => (
                    <button
                      key={chip}
                      onClick={() => setPrompt(p => p + ` with ${chip.replace('+ ', '').toLowerCase()}`)}
                      className="rounded-full border border-violet-200 bg-violet-50 px-2.5 py-1 text-xs font-medium text-violet-700 hover:bg-violet-100"
                    >
                      {chip}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Templates */}
          <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div className="border-b border-slate-100 px-4 py-3">
              <h2 className="text-sm font-bold text-slate-900">Quick Templates</h2>
            </div>
            <div className="grid grid-cols-2 gap-2 p-3">
              {PROMPT_TEMPLATES.map((template) => (
                <button
                  key={template.id}
                  onClick={() => {
                    setPrompt(template.prompt);
                    setEnvVars(template.envVarHints.map(name => ({ name, value: '', isSecret: name.includes('TOKEN') || name.includes('KEY') || name.includes('SECRET') })));
                  }}
                  className="flex items-center gap-2 rounded-xl border border-slate-100 bg-slate-50 p-3 text-left transition-all hover:border-violet-200 hover:bg-violet-50"
                >
                  <span className="text-xl">{template.icon}</span>
                  <div>
                    <p className="text-xs font-bold text-slate-900">{template.name}</p>
                    <p className="text-[10px] text-slate-500 truncate">{template.description}</p>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Transport selector */}
          <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div className="border-b border-slate-100 px-4 py-3">
              <h2 className="text-sm font-bold text-slate-900">Transport Layer</h2>
            </div>
            <div className="space-y-2 p-3">
              {([
                { id: 'stdio' as TransportType, label: 'stdio', desc: 'Recommended — works with all MCP clients', badge: 'Most compatible', isPro: false },
                { id: 'sse' as TransportType, label: 'SSE', desc: 'Server-Sent Events — real-time streaming', badge: 'Pro', isPro: true },
                { id: 'http' as TransportType, label: 'HTTP', desc: 'Stateless HTTP — API-style usage', badge: 'Pro', isPro: true },
              ]).map(({ id, label, desc, badge, isPro }) => (
                <label
                  key={id}
                  onClick={() => {
                    if (isPro && plan === 'free') {
                      dispatch({ type: 'OPEN_UPGRADE_MODAL', payload: 'feature_locked' });
                    } else {
                      setTransport(id);
                    }
                  }}
                  className={cn(
                    'flex cursor-pointer items-start gap-3 rounded-xl border p-3 transition-all',
                    transport === id
                      ? 'border-violet-300 bg-violet-50'
                      : 'border-slate-200 bg-white hover:border-slate-300',
                    isPro && plan === 'free' && 'opacity-60'
                  )}
                >
                  <div className={cn(
                    'mt-0.5 flex h-4 w-4 flex-shrink-0 items-center justify-center rounded-full border-2',
                    transport === id ? 'border-violet-500' : 'border-slate-300'
                  )}>
                    {transport === id && <div className="h-2 w-2 rounded-full bg-violet-500" />}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-semibold text-slate-900">{label}</span>
                      <span className={cn(
                        'rounded-full px-2 py-0.5 text-[10px] font-bold',
                        isPro ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-emerald-700'
                      )}>
                        {badge}
                      </span>
                    </div>
                    <p className="text-xs text-slate-400">{desc}</p>
                  </div>
                </label>
              ))}
            </div>
          </div>

          {/* Environment variables */}
          <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div className="flex items-center justify-between border-b border-slate-100 px-4 py-3">
              <div>
                <h2 className="text-sm font-bold text-slate-900">Environment Variables</h2>
                <p className="text-xs text-slate-400">API keys, tokens, and config values</p>
              </div>
              <button
                onClick={addEnvVar}
                className="flex items-center gap-1 rounded-lg bg-violet-50 px-2.5 py-1.5 text-xs font-semibold text-violet-700 hover:bg-violet-100"
              >
                <Plus className="h-3.5 w-3.5" />
                Add
              </button>
            </div>
            <div className="space-y-2 p-3">
              {envVars.length === 0 ? (
                <button
                  onClick={addEnvVar}
                  className="flex w-full flex-col items-center gap-1.5 rounded-xl border-2 border-dashed border-slate-200 p-4 text-slate-400 hover:border-violet-300 hover:text-violet-500"
                >
                  <Plus className="h-5 w-5" />
                  <span className="text-xs font-medium">Add environment variable</span>
                </button>
              ) : (
                envVars.map((envVar, i) => (
                  <EnvVarRow
                    key={i}
                    envVar={envVar}
                    index={i}
                    onChange={updateEnvVar}
                    onRemove={removeEnvVar}
                  />
                ))
              )}
            </div>
          </div>

          {/* Generate button */}
          <button
            onClick={handleGenerate}
            disabled={genState === 'generating' || genState === 'validating' || prompt.trim().length < 10}
            className={cn(
              'flex w-full items-center justify-center gap-3 rounded-2xl py-4 text-base font-bold transition-all',
              'disabled:cursor-not-allowed disabled:opacity-50',
              genState === 'generating' || genState === 'validating'
                ? 'bg-gradient-to-r from-violet-400 to-indigo-400 text-white'
                : 'bg-gradient-to-r from-violet-600 to-indigo-600 text-white shadow-lg shadow-violet-200 hover:shadow-xl hover:shadow-violet-300 hover:scale-[1.02]'
            )}
          >
            {genState === 'generating' || genState === 'validating' ? (
              <>
                <Loader2 className="h-5 w-5 animate-spin" />
                {progressLabel}...
              </>
            ) : (
              <>
                <Sparkles className="h-5 w-5" />
                Generate MCP Server
                <span className="ml-1 rounded-md bg-white/20 px-2 py-0.5 text-xs">⌘↵</span>
              </>
            )}
          </button>

          {/* Progress bar */}
          {(genState === 'generating' || genState === 'validating') && (
            <div>
              <div className="mb-1 flex justify-between text-xs text-slate-500">
                <span>{progressLabel}</span>
                <span>{Math.round(progress)}%</span>
              </div>
              <div className="h-2 w-full overflow-hidden rounded-full bg-slate-100">
                <div
                  className="h-full rounded-full bg-gradient-to-r from-violet-500 to-indigo-500 transition-all duration-300"
                  style={{ width: `${progress}%` }}
                />
              </div>
            </div>
          )}
        </div>

        {/* Right panel — Output */}
        <div className="xl:col-span-3">
          {genState === 'idle' && !result && (
            <div className="flex h-full min-h-[500px] flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-200 bg-white p-12 text-center">
              <div className="mx-auto mb-4 flex h-20 w-20 items-center justify-center rounded-3xl bg-gradient-to-br from-violet-100 to-indigo-100">
                <Terminal className="h-10 w-10 text-violet-400" />
              </div>
              <h3 className="text-lg font-bold text-slate-900">Your server will appear here</h3>
              <p className="mt-2 max-w-sm text-sm text-slate-400">
                Fill in your prompt and click "Generate MCP Server". The AI will create
                production-ready TypeScript in seconds.
              </p>
              <div className="mt-6 space-y-2 text-left">
                {['Describe your MCP server above', 'Add any required API keys', 'Click Generate (or press ⌘+Enter)'].map((step, i) => (
                  <div key={i} className="flex items-center gap-3">
                    <span className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-violet-100 text-xs font-bold text-violet-600">
                      {i + 1}
                    </span>
                    <span className="text-sm text-slate-500">{step}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {(genState === 'generating' || genState === 'validating') && (
            <div className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden">
              <div className="border-b border-slate-100 px-5 py-4">
                <div className="flex items-center gap-3">
                  <Loader2 className="h-5 w-5 animate-spin text-violet-600" />
                  <span className="text-sm font-bold text-slate-900">
                    {genState === 'generating' ? 'Generating your MCP server...' : 'Validating code...'}
                  </span>
                </div>
              </div>
              {/* Skeleton */}
              <div className="bg-slate-950 p-6 font-mono text-sm space-y-2 min-h-[400px]">
                <div className="text-violet-400">// Generating TypeScript...</div>
                {Array.from({ length: 20 }).map((_, i) => (
                  <div
                    key={i}
                    className="h-4 animate-pulse rounded bg-slate-800"
                    style={{ width: `${30 + Math.random() * 60}%`, animationDelay: `${i * 50}ms` }}
                  />
                ))}
              </div>
            </div>
          )}

          {result && (genState === 'complete' || genState === 'error') && (
            <div className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden">
              {/* Tabs */}
              <div className="border-b border-slate-100 flex items-center justify-between px-4">
                <div className="flex">
                  {(['code', 'validation', 'readme'] as const).map((tab) => (
                    <button
                      key={tab}
                      onClick={() => setActiveTab(tab)}
                      className={cn(
                        'border-b-2 px-4 py-3.5 text-sm font-semibold capitalize transition-colors',
                        activeTab === tab
                          ? 'border-violet-500 text-violet-700'
                          : 'border-transparent text-slate-500 hover:text-slate-700'
                      )}
                    >
                      {tab === 'validation' ? (
                        <span className="flex items-center gap-1.5">
                          Validation
                          {result.validationReport.passed ? (
                            <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" />
                          ) : (
                            <AlertTriangle className="h-3.5 w-3.5 text-amber-500" />
                          )}
                        </span>
                      ) : tab.charAt(0).toUpperCase() + tab.slice(1)}
                    </button>
                  ))}
                </div>

                {/* Code toolbar */}
                {activeTab === 'code' && (
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-slate-400">
                      {formatDuration(result.generationTimeMs)}
                    </span>
                    <button
                      onClick={handleCopy}
                      className="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-slate-50 px-3 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-100"
                    >
                      {copied ? <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
                      {copied ? 'Copied!' : 'Copy'}
                    </button>
                    <button
                      onClick={handleDownload}
                      className="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-slate-50 px-3 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-100"
                    >
                      <Download className="h-3.5 w-3.5" />
                      Download
                    </button>
                  </div>
                )}
              </div>

              {/* Code view */}
              {activeTab === 'code' && (
                <div className="relative">
                  {/* Code stats bar */}
                  <div className="flex items-center gap-3 border-b border-slate-800 bg-slate-900 px-4 py-2">
                    <span className="text-xs text-slate-400">
                      {result.generatedCode.split('\n').length} lines
                    </span>
                    <span className="text-slate-700">·</span>
                    <span className="text-xs text-slate-400">
                      {result.config.tools.length || result.generatedCode.match(/name: "/g)?.length || 0} tools
                    </span>
                    <span className="text-slate-700">·</span>
                    <ValidationBadge score={result.validationReport.score} />
                  </div>
                  <pre className="overflow-auto bg-slate-950 p-5 text-xs leading-relaxed text-slate-300 max-h-[600px]">
                    <code>{result.generatedCode}</code>
                  </pre>
                </div>
              )}

              {/* Validation view */}
              {activeTab === 'validation' && (
                <div className="p-5 space-y-4">
                  {/* Status banner */}
                  <div className={cn(
                    'flex items-center gap-3 rounded-xl p-4',
                    result.validationReport.passed ? 'bg-emerald-50 border border-emerald-200' : 'bg-amber-50 border border-amber-200'
                  )}>
                    {result.validationReport.passed ? (
                      <CheckCircle2 className="h-5 w-5 text-emerald-600" />
                    ) : (
                      <AlertTriangle className="h-5 w-5 text-amber-600" />
                    )}
                    <div>
                      <p className={cn('text-sm font-bold', result.validationReport.passed ? 'text-emerald-800' : 'text-amber-800')}>
                        {result.validationReport.passed
                          ? '✓ Validation Passed — Ready to Deploy'
                          : '⚠ Warnings Detected — Review Before Deploying'}
                      </p>
                      <p className="text-xs text-slate-500">
                        Quality score: {result.validationReport.score}/100 · {result.validationReport.readinessLevel}
                      </p>
                    </div>
                  </div>

                  {/* Score meter */}
                  <div className="rounded-xl border border-slate-200 p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-semibold text-slate-700">Code Quality Score</span>
                      <ValidationBadge score={result.validationReport.score} />
                    </div>
                    <div className="h-3 w-full overflow-hidden rounded-full bg-slate-100">
                      <div
                        className={cn(
                          'h-full rounded-full transition-all',
                          result.validationReport.score >= 90 ? 'bg-emerald-500' :
                          result.validationReport.score >= 70 ? 'bg-blue-500' :
                          result.validationReport.score >= 50 ? 'bg-amber-500' : 'bg-red-500'
                        )}
                        style={{ width: `${result.validationReport.score}%` }}
                      />
                    </div>
                  </div>

                  {/* Checks */}
                  <div className="space-y-2">
                    {[
                      { label: 'TypeScript syntax valid', passed: result.validationReport.syntaxErrors.length === 0 },
                      { label: 'MCP structure correct', passed: result.validationReport.structuralWarnings.length === 0 },
                      { label: 'No security flags', passed: result.validationReport.securityFlags.length === 0 },
                      { label: 'Dependencies allowed', passed: !result.validationReport.detectedDependencies.some(d => d.startsWith('blocked')) },
                      { label: 'Environment vars declared', passed: result.validationReport.envVarReport.undeclared.length === 0 },
                    ].map(({ label, passed }) => (
                      <div key={label} className="flex items-center gap-2.5 rounded-lg border border-slate-100 bg-slate-50 px-3 py-2.5">
                        {passed ? (
                          <CheckCircle2 className="h-4 w-4 text-emerald-500" />
                        ) : (
                          <XCircle className="h-4 w-4 text-red-500" />
                        )}
                        <span className="text-sm text-slate-700">{label}</span>
                      </div>
                    ))}
                  </div>

                  {/* Dependencies */}
                  {result.validationReport.detectedDependencies.length > 0 && (
                    <div className="rounded-xl border border-slate-200 p-4">
                      <div className="flex items-center gap-2 mb-3">
                        <Package className="h-4 w-4 text-slate-500" />
                        <span className="text-sm font-semibold text-slate-700">Detected Dependencies</span>
                      </div>
                      <div className="flex flex-wrap gap-2">
                        {result.validationReport.detectedDependencies.map(dep => (
                          <span key={dep} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-mono text-slate-700">
                            {dep}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Suggestions */}
                  {result.validationReport.suggestions.length > 0 && (
                    <div className="rounded-xl border border-blue-200 bg-blue-50 p-4">
                      <p className="text-sm font-semibold text-blue-800 mb-2">💡 Improvement suggestions</p>
                      <ul className="space-y-1">
                        {result.validationReport.suggestions.map((s, i) => (
                          <li key={i} className="text-xs text-blue-700">
                            {i + 1}. {s}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Token usage */}
                  <div className="rounded-xl border border-slate-200 p-4">
                    <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Generation Stats</p>
                    <div className="grid grid-cols-3 gap-3">
                      <div>
                        <p className="text-sm font-bold text-slate-900">{result.tokenUsage.promptTokens.toLocaleString()}</p>
                        <p className="text-xs text-slate-400">Prompt tokens</p>
                      </div>
                      <div>
                        <p className="text-sm font-bold text-slate-900">{result.tokenUsage.completionTokens.toLocaleString()}</p>
                        <p className="text-xs text-slate-400">Completion tokens</p>
                      </div>
                      <div>
                        <p className="text-sm font-bold text-slate-900">{formatDuration(result.generationTimeMs)}</p>
                        <p className="text-xs text-slate-400">Total time</p>
                      </div>
                    </div>
                    <p className="mt-2 text-xs text-slate-400">Model: {result.tokenUsage.modelUsed}</p>
                  </div>
                </div>
              )}

              {/* README view */}
              {activeTab === 'readme' && (
                <div className="p-5">
                  <div className="rounded-xl border border-slate-200 bg-slate-50 p-5 font-mono text-xs text-slate-700 whitespace-pre-wrap max-h-[600px] overflow-auto">
{`# ${result.config.serverName} MCP Server

Generated by [MCPForge](https://mcpforge.dev) — Build MCP servers with AI.

## Overview

${prompt.slice(0, 200)}

## Installation

\`\`\`bash
npm install @modelcontextprotocol/sdk zod
npx tsx ${result.config.serverName.toLowerCase()}.ts
\`\`\`

## Environment Variables

| Variable | Required | Description |
|----------|----------|-------------|
${envVars.map(e => `| \`${e.name}\` | ✓ | ${e.isSecret ? 'Secret — encrypt at rest' : 'Configuration value'} |`).join('\n') || '| None required | — | — |'}

## Available Tools

${(result.generatedCode.match(/name: "([^"]+)"/g) || []).map(m => {
  const name = m.replace('name: "', '').replace('"', '');
  return `### \`${name}\`\n\nExecute the ${name.replace(/_/g, ' ')} operation.\n`;
}).join('\n')}

## Usage with Claude Desktop

Add to your \`claude_desktop_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "${result.config.serverName.toLowerCase()}": {
      "command": "node",
      "args": ["path/to/${result.config.serverName.toLowerCase()}.js"],
      "env": {
        ${envVars.map(e => `"${e.name}": "your_${e.name.toLowerCase()}"`).join(',\n        ')}
      }
    }
  }
}
\`\`\`

## Deploy to MCPForge

[![Deploy to MCPForge](https://mcpforge.dev/badge.svg)](https://mcpforge.dev/deploy)

---
*Generated at ${new Date().toLocaleDateString()} · Score: ${result.validationReport.score}/100*`}
                  </div>
                </div>
              )}

              {/* CTA row */}
              <div className="border-t border-slate-100 flex items-center justify-between gap-4 px-5 py-4">
                <button
                  onClick={() => {
                    setPrompt('');
                    setResult(null);
                    setGenState('idle');
                    setProgress(0);
                  }}
                  className="flex items-center gap-2 text-sm text-slate-500 hover:text-slate-700"
                >
                  <RefreshCw className="h-4 w-4" />
                  Start over
                </button>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => onNavigate('servers')}
                    className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50"
                  >
                    View My Servers
                  </button>
                  <button
                    onClick={() => {
                      dispatch({
                        type: 'ADD_NOTIFICATION',
                        payload: { id: Date.now().toString(), type: 'success', title: 'Server deployed!', message: 'Your MCP server is live and ready to connect.', timestamp: new Date().toISOString() }
                      });
                    }}
                    className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 px-4 py-2 text-sm font-bold text-white"
                  >
                    <Zap className="h-4 w-4" />
                    Deploy Live
                    <ArrowRight className="h-4 w-4" />
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
